### ISSUE TITLE
なにこのえらー

### ISSUE THREAD

**Issue by TaigaNatto** [TaigaNatto/MatoMemo#48]
Process: com.example.t_robop.matomemo, PID: 14280
                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.t_robop.matomemo/com.example.t_robop.matomemo.MatomeActivity}: java.lang.ArrayIndexOutOfBoundsException: rowIndex > available rows: 0 > 0
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
                                                                                  at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                               Caused by: java.lang.ArrayIndexOutOfBoundsException: rowIndex > available rows: 0 > 0
                                                                                  at io.realm.internal.TableView.nativeGetSourceRowIndex(Native Method)
                                                                                  at io.realm.internal.TableView.getSourceRowIndex(TableView.java:111)
                                                                                  at io.realm.RealmResults.get(RealmResults.java:215)
                                                                                  at com.example.t_robop.matomemo.MatomeActivity.onCreate(MatomeActivity.java:78)
                                                                                  at android.app.Activity.performCreate(Activity.java:6955)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045) 
                                                                                  at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:154) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6776) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by Dai1678** [comment]
どんな状況で何したらエラーが出たのかちゃんと書いてください（#^ω^）

**Comment by TaigaNatto** [comment]
直りましたー！Realm書き換えたのにアプリアンインストールしてなかったのが原因でした！＼(^o^)／
