### ISSUE TITLE
xmlで定義したダイアログをviewで呼ぶときにバグります

### ISSUE THREAD

**Issue by Kawaguchi410** [TaigaNatto/MatoMemo#92]
https://github.com/TaigaNatto/MatoMemo/commit/c999e5bd1648f79535602d220b9622cc3c32e0cd
72行目で宣言して、89行目で関連ずけたviewを
126行目に使うメソッドで442行目でダイアログに設定し
別のダイアログに373行目で設定すると落ちます。

これをかいけつするには
xmlのファイルを追加しなくてはならないでしょうか？

**Comment by TaigaNatto** [comment]
エラーをコピペして貼ることはできますか？
また、行数を言われてもコードによって変わってしまうので、せめてその行のメソッドだけでも書いてくれると助かります。

**Comment by Kawaguchi410** [comment]
main
                                                 Process: com.example.t_robop.matomemo, PID: 3634
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.t_robop.matomemo/com.example.t_robop.matomemo.StartListActivity}: io.realm.exceptions.RealmMigrationNeededException: RealmMigration must be provided
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                  Caused by: io.realm.exceptions.RealmMigrationNeededException: RealmMigration must be provided
                                                     at io.realm.BaseRealm.migrateRealm(BaseRealm.java:612)
                                                     at io.realm.Realm.migrateRealm(Realm.java:1513)
                                                     at io.realm.Realm.createInstance(Realm.java:272)
                                                     at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:143)
                                                     at io.realm.Realm.getDefaultInstance(Realm.java:210)
                                                     at com.example.t_robop.matomemo.StartListActivity.onCreate(StartListActivity.java:79)
                                                     at android.app.Activity.performCreate(Activity.java:6662)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:154) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
                                                  Caused by: io.realm.exceptions.RealmMigrationNeededException: Field count is less than expected - expected 6 but was 5
                                                     at io.realm.RealmMatomeEntityRealmProxy.validateTable(RealmMatomeEntityRealmProxy.java:382)
                                                     at io.realm.DefaultRealmModuleMediator.validateTable(DefaultRealmModuleMediator.java:81)
                                                     at io.realm.Realm.initializeRealm(Realm.java:343)
                                                     at io.realm.Realm.createAndValidate(Realm.java:300)
                                                     at io.realm.Realm.createInstance(Realm.java:265)
                                                     at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:143) 
                                                     at io.realm.Realm.getDefaultInstance(Realm.java:210) 
                                                     at com.example.t_robop.matomemo.StartListActivity.onCreate(StartListActivity.java:79) 
                                                     at android.app.Activity.performCreate(Activity.java:6662) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:154) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 

コードは

if (dialogNewMakeGroup == null) {
             dialogNewMakeGroup = new AlertDialog.Builder(this)
                     .setView(inputView)←これをした後に

        if (dialogReferenceGroup == null) {
             dialogReferenceGroup = new AlertDialog.Builder(this)
                     .setView(inputView)←べつのダイアログにviewを入れるとアプリが落ちます

**Comment by TaigaNatto** [comment]
別のxmlの場合はエラー吐かない？
もともと別のxmlつくる予定じゃなかったっけ

**Comment by Kawaguchi410** [comment]
二つxmlを用意したら解決しました

**Comment by TaigaNatto** [comment]
良かった
closeしよう
